language: clojure
lein: lein
script: lein build-site
branches:
  only:
  - master
jdk:
- openjdk7
- openjdk6
addons:
  ssh_known_hosts: vps.jmgpena.net
before_install:
- openssl aes-256-cbc -K $encrypted_1f469ef81ca4_key -iv $encrypted_1f469ef81ca4_iv -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
after_success:
- rsync -rv --delete -e "ssh -i deploy_key" export/ jmgpena@vps.jmgpena.net:~/jmgpena.net
